export default {
  SET_CATEGORY_FILTER: "SET_CATEGORY_FILTER",
  SET_PRICE_FILTER:"SET_PRICE_FILTER",
  REMOVE_FILTER: "REMOVE_FILTER",
  ADD_CART: "ADD_CART",
  CLEAR_CART: "CLEAR_CART",
  DROPDOWN_TOGGLED: "DROPDOWN_TOGGLED",
  SORT:"SORT"
};
